name: genswap
description: "Connect generations through language! GenSwap translates slang and phrases across Gen Z, Millennials, Gen X, Boomers, etc., making communication fun and effortless."
publish_to: 'none'
version: 1.1.1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  rounded_loading_button: 
      git:
        url: https://github.com/scopendo/flutter_rounded_loading_button.git
        ref: master
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.5
  flutter_svg: ^2.0.10+1
  typewritertext: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/undraw_night_calls.svg
